name: jumpvalues
description: "A new Flutter project."
publish_to: 'none'
# version: 2.0.3+4
# 2.0.3 is version name and 4 is build number
version: 3.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_mobx: ^2.0.6+5
  flutter_pannable_rating_bar: ^2.7.2+1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  mobx: ^2.2.0
  nb_utils: ^6.1.3
  permission_handler: ^10.4.0
  phone_numbers_parser: ^8.3.0
  syncfusion_flutter_calendar: ^26.1.38
  twilio_programmable_video: ^1.1.1
  webview_flutter: ^4.7.0
  socket_io_client: ^2.0.3+1
  flutter_background_service: ^5.0.9
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

  hive_generator: ^2.0.1
  mobx_codegen: ^2.6.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/ic_launcher.png"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
