name: jumpvalues
description: "A new Flutter project."
publish_to: 'none'
# version: 2.0.3+4
# 2.0.3 is version name and 4 is build number
version: 3.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  flutter_mobx: ^2.0.6+5
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  mobx: ^2.2.0
  nb_utils: ^6.1.3
  syncfusion_flutter_calendar: ^26.1.38
  twilio_programmable_video: ^1.1.1
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/ic_launcher.png"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
