storePassword=flutter
keyPassword=flutter
keyAlias=jumpcc
storeFile=/Users/hstpl_lap_335/Documents/projects/jumpvalues/android/jump-keystore.jks
# keytool -genkey -v -keystore jump-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias jumpcc





# From Android Studio==
# Variant: release
# Config: release
# Store: /Users/hstpl_lap_335/Documents/projects/jumpvalues/android/jump-keystore.jks
# Alias: jumpcc
# MD5: F7:2D:6C:81:EE:79:8F:15:4C:F0:3B:5D:FA:51:90:8D
# SHA1: 79:DC:1D:7E:90:C8:2C:8A:CB:20:DB:62:17:30:F2:5B:D5:29:D5:5A
# SHA-256: 39:75:BA:47:C3:E9:5C:A6:6C:44:4A:9A:20:B1:D9:B7:7C:C0:D5:2B:07:FE:78:0B:32:77:C8:94:6A:12:D7:EC
# Valid until: Friday, 9 February 2052

# From Play Console==
# MD5 certificate fingerprint = FB:5A:BF:B7:B6:B4:DD:05:F4:B3:3E:C1:97:86:4A:81
# SHA-1 certificate fingerprint = F6:36:83:40:3E:22:A1:FA:39:09:40:20:2C:50:25:A6:4F:BA:B8:A6
# SHA-256 certificate fingerprint = 6B:E0:15:1F:61:26:9A:88:F6:2D:06:20:9B:69:91:E4:EE:E8:48:B5:AE:A7:22:64:6D:94:5D:91:B9:3A:C7:15