const USERTYPE_CLIENT = 'client';
const USERTYPE_COACH = 'coach';

const IS_LOGGED_IN = 'IS_LOGGED_IN';
const TOKEN = 'TOKEN';
const USER_TYPE = 'USER_TYPE';
const USER_ID = 'USER_ID';
const FIRST_NAME = 'FIRST_NAME';
const LAST_NAME = 'LAST_NAME';
const CONTACT_NUMBER = 'CONTACT_NUMBER';
const USER_EMAIL = 'USER_EMAIL';
const USER_COMPANY = 'USER_COMPANY';
const USER_POSITION = 'USER_POSITION';
const PROFILE_IMAGE = 'PROFILE_IMAGE';
const USER_ABOUT_ME = 'USER_ABOUT_ME';
