const USERTYPE_CLIENT = 'Client';
const USERTYPE_COACH = 'Coach';

const IS_LOGGED_IN = 'IS_LOGGED_IN';
const USER_TYPE = 'USER_TYPE';
const TOKEN = 'TOKEN';
const ID = 'ID';
const USER_ID = 'USER_ID';
const SPONSOR_ID = 'SPONSOR_ID';
const SPONSOR_NAME = 'SPONSOR_NAME';
const USER_FIRST_NAME = 'USER_FIRST_NAME';
const USER_LAST_NAME = 'USER_LAST_NAME';
const USER_CONTACT_NUMBER = 'USER_CONTACT_NUMBER';
const USER_EDUCATION = 'USER_EDUCATION';
const USER_PREFER_VIA = 'USER_PREFER_VIA';
const USER_PHILOSOPHY = 'USER_PHILOSOPHY';
const USER_CERTIFICATIONS = 'USER_CERTIFICATIONS';
const USER_INDUSTRIES_SERVED = 'USER_INDUSTRIES_SERVED';
const USER_EXPERIANCE = 'USER_EXPERIANCE';
const USER_NICHE = 'USER_NICHE';

const USER_EMAIL = 'USER_EMAIL';
const USER_COMPANY = 'USER_COMPANY';
const USER_POSITION = 'USER_POSITION';
const PROFILE_IMAGE = 'PROFILE_IMAGE';
const USER_ABOUT_ME = 'USER_ABOUT_ME';
